spring:
  application:
    name: tbtb-zuul-server
  #这个表示在响应非正常情况时,表示开启重试机制
  cloud:
    loadbalancer:
      retry:
        enabled: true

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: zuul   #自定义服务名称信息  启动多个服务做集群需要设置为不同的ID值
    prefer-ip-address: true   #访问路径可以显示IP地址

zuul:
  routes:
    API-A:
      path: /oa/**
      serviceId: tbtb-oa #指向的服务名称
    API-B:
      path: /dict/**
      serviceId: tbtb-dictionary
  ##防跨域请求
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Credentials,Access-Control-Allow-Origin,Vary,X-Frame-Options
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时


##目的：防止服务重启后，第一次访问超时
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
          strategy: SEMAPHORE #Request请求头设置token
ribbon:
  #正常情况下，当客户端向服务器端发送请求时,如果网络很差,就会无法响应内容,这里可以设置为1分钟,如果1分钟访问不到则抛出超时异常
  ReadTimeout: 10000
  #这个指建立连接所用的时间,适应于网络正常情况下，如果1分钟未建立连接,抛出异常
  ConnectTimeout: 10000