spring:
  application:
    name: tbtb-zuul-server

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: zuul   #自定义服务名称信息  启动多个服务做集群需要设置为不同的ID值
    prefer-ip-address: true   #访问路径可以显示IP地址

zuul:
  routes:
    API-A:
      path: /oa/**
      serviceId: tbtb-oa #指向的服务名称
    API-B:
      path: /test/**
      serviceId: tbtb-test #指向的服务名称
  ##防跨域请求
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Credentials,Access-Control-Allow-Origin,Vary,X-Frame-Options,token

##目的：防止服务重启后，第一次访问超时
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
          strategy: SEMAPHORE #Request请求头设置token